#!/usr/bin/env python
# coding: utf-8

# 1. In the below elements which of them are values or an expression? eg:- values can be
# integer or string and expressions will be mathematical operators.
# *
# &#39;hello&#39;
# -87.8
# -
# /
# +
# 6

# ans. 'hello', -87.8 are values
# and -,/,+ are expressions

# #2. What is the difference between string and variable?
# ans. Strings are words written in "" quotes and variables can be called as containers that contains some values given by the users

# ans. Strings are words written in "" quotes and variables can be called as containers that contains some values given by the users
# 

# #3 Describe three different data types.

# ans. 1 List- multiple numbers or strings can be stored in it and it is denoted by[].
# 2. Integers- all the numeric values are called as integers
# 3.Float: decimal numbers are called as float data type

# 4. What is an expression made up of? What do all expressions do?

# ans.expression are madeup of some values which performs mathematical operations like addition subtractions division etc. + - / % are example of expressions.
# 

# 5. This assignment statements, like spam = 10. What is the difference between an
# expression and a statement?

# ans.expression are madeup of some values  which performs mathematical operations like addition subtractions division etc and statement is a command to the python to execute the operations given by the users.
# 

# 6. After running the following code, what does the variable bacon contain?
# bacon = 22
# bacon + 1

# ans. 

# In[5]:


bacon= 22


# In[6]:


bacon+ 1


# it contains 23 bacon

# 7. What should the values of the following two terms be?
# 'spam' + 'spamspam'
# 'spam'*3

# In[9]:


'spam' + 'spamspam'


# In[10]:


'spam'*3


# three times 'spamspamspam'

# 8. Why is eggs a valid variable name while 100 is invalid?

# ans. variables cant be declare with numbers or intergers it must start with some alphabets it is a bulit in rule.

# 9. What three functions can be used to get the integer, floating-point number, or string
# version of a value?

# int(), float(),str()

# 10. Why does this expression cause an error? How can you fix it?
# 'I have eaten' + 99 +  'burritos'

# integer and string cannot be merged or concatinate directly , user has to do type casting in order to join integer and string.

# In[ ]:




